#! /bin/sh
$HOME/.config/screenlayout/display.sh
sxhkd &
picom -b --experimental-backends &
xrdb ~/.Xresources &
$HOME/.config/.fehbg &
$HOME/.config/polybar/launch.sh &
$HOME/.config/.hdmi.sh &
nm-applet --no-agent &

###---MONITORS---###
bspc monitor eDP1 -d www code term vid
bspc monitor DP1 -d 5 6 7 8 9 0

###---GLOBAL SETTINGS---###
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier shift
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config normal_border_color "#676E95"
bspc config active_border_color   "#C792EA"
bspc config focused_border_color  "#C792EA"
bspc config presel_feedback_color "#6272a4"

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true


bspc config border_width         4
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a telegram-desktop desktop='^2' border=off
bspc rule -a TelegramDesktop desktop='^2'

bspc rule -a Chromium desktop='^3'
bspc rule -a mpv state=fullscreen
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rile -a Zathura state=titled
